.PHONY: clean All

All:
	@echo "----------Building project:[ SimViewer - Debug ]----------"
	@$(MAKE) -f  "SimViewer.mk"
clean:
	@echo "----------Cleaning project:[ SimViewer - Debug ]----------"
	@$(MAKE) -f  "SimViewer.mk" clean
