.PHONY: clean All

All:
	@echo "----------Building project:[ RPCServer - Debug ]----------"
	@$(MAKE) -f  "RPCServer.mk"
clean:
	@echo "----------Cleaning project:[ RPCServer - Debug ]----------"
	@$(MAKE) -f  "RPCServer.mk" clean
